### ISSUE TITLE
Integaration not working for me

### ISSUE THREAD

**Issue by micro521** [frlequ/mibox_socket#1]
Hi,

I have installed your integration on my HA which is running on RPi4.
I added the BT MAC of my Xiaomi MiBox 4S found in the settings menu of the Android player but the player does not wake up.

I checked the bluetoothctl and I didn't find any line with the MAC added to the configuration. Should I see any line related to the pairing attempt?

Can you help me how to proceed with the fault isolation?

Thanks in advance.

**Comment by frlequ** [comment]
Please check that you don't use RPI4 bluetooth with any other components, even default ones could cause problems. Disable if possible. 

> Should I see any line related to the pairing attempt?

yes, paring attempt should be made (confirmation skipped). That should be enough to wake up device.

if you have access to _bluetoothctl_, you can try manually:

```
bluetoothctl
scan on
pair <mac_address>
```

**Comment by micro521** [comment]
Thanks for your response.
I just disabled HA's default Bluetooth integration.
Still no success.

I tried manual commands but it is not working. I get "Device <MAC> not available.
Can I confrm somehow the BT MAC ellse than the GUI in MiBox?

**Comment by frlequ** [comment]
> I tried manual commands but it is not working. I get "Device not available

After `scan on` command in `bluetoothctl`, do you see your device MAC? It should appear in the list. If not, then there is some other problem.

**Comment by micro521** [comment]
I had some test and I can see that the MiBox can bee seen in the scan once NEW and once DEL after it is rebooted. Later it is silent. I have already turned off all other integrations using BT. I had Android TV remote but it is deleted for the MiBox.
I have a Mi TV Stick as well. Its MAC is visble periodically in the scan and your integration is working with it. So I guess the MiBox is not adverising its MAC after reboot. I don't know why it is happening. It is a MiBox 4 version 9.

**Comment by frlequ** [comment]
Strange. Mibox should always cast a BT MAC, it's the only way you can use default remote control. I don't have many ideas why you cannot see BT MAC under `scan on`.

1. You should have default remote pared under `Mibox -> options -> Remotes & Accessories`. I'm not shure if it works without it.
2. Be sure you **do not have** a RPI paired under the same menu `Mibox -> options -> Remotes & Accessories`. Delete if present.
3. Check range of devices. They should be as close as possible.

**Comment by micro521** [comment]
There is only one remote un the menu, the Xiaomi RC.
I played with the renage and relocated the MiBox but it is the same.
I will try now a factory reset.

**Comment by micro521** [comment]
After the factory reset of the MiBox it started working. I will keep testing as I don't see if it works all the time but most of the time it does.
Thanks for your help.

**Comment by frlequ** [comment]
Great! Nice to hear that.
